Update firebase-preview.yml

diff --git a/.github/workflows/firebase-preview.yml b/.github/workflows/firebase-preview.yml
--- a/.github/workflows/firebase-preview.yml
+++ b/.github/workflows/firebase-preview.yml
@@ -21,7 +21,7 @@ jobs:
 
       - name: Build Project
         run: |
-          npm run build || { echo "Build failed!"; exit 1; }
+          CI=false npm run build || { echo "Build failed!"; exit 1; }
 
       - name: Debug - Check if build folder exists
         run: |
